spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          default-label: ${GIT_BRANCH}
          ignoreLocalSshSettings: true
          searchPaths:
            - '{application}'
            - '{application}/{profile}'
          privateKey: ${SSH_KEY}

  security:
      user:
        name: ${CONFIG_SERVER_USERNAME}
        password: ${CONFIG_SERVER_PASSWORD}